defaultBranch: 'develop'
branchName: '${issue.number}'
branches:
  - label: 🛠 refactor
    prefix: refactor/
  - label: 🐞 bug
    prefix: bugfix/
  - label: '*'
    prefix: issues/
autoCloseIssue: true