services:
  app:
    image: ${DOCKERHUB_USERNAME}/my-spring-app:latest
    container_name: ${PROJECT_NAME}-app
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/health || curl -f http://localhost:8080/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - /home/ubuntu/my-app/firebase-key.json:/app/firebase/firebase-key.json
    networks:
      - shared_net

networks:
  shared_net:
    external: true
