version: "3.8"

services:
  app:
    image: ${DOCKERHUB_USERNAME}/my-spring-app:latest
    container_name: ${PROJECT_NAME}-app
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: jdbc:mysql://<EC2-PRIVATE-IP>:3306/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: <EC2-PRIVATE-IP>
      SPRING_REDIS_PORT: 6379
