spring:
  application:
    name: ne-ne-challenge

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  error:
    include-message: always

jwt:
  secret:
    key: ${SECRET_KEY}

external:
  base-url: ${INTERNAL_BASE_URL}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
