global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Docker 사용 시
      # 또는 Spring Boot가 Docker 밖에서 실행되면 'localhost:8080'
